spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          configuration:
            security:
              protocol: PLAINTEXT
      output-bindings: test-out
      bindings:
        test-out:
          destination: eogov-test
          producer:
            auto-startup: true

refarch:
  s3:
    url: http://localhost:9000
    bucket-name: eogov-bucket
    access-key: minio
    secret-key: Test1234
