spring:
  security:
    user:
      name: for
      # pw: password
      password: "{bcrypt}$2a$12$eQgzAB2v.y8lkVqfOjOaL.acj1Zp8HW87CNdHzdyOaoYqnHL0Tppy"
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          configuration:
            security:
              protocol: PLAINTEXT
      output-bindings: test-out
      bindings:
        test-out:
          destination: eogov-test
          producer:
            auto-startup: true

refarch:
  s3:
    url: http://localhost:9000
    bucket-name: eogov-bucket
    access-key: minio
    secret-key: Test1234
